import type { Metadata } from "next";
import { IBM_Plex_Sans_Arabic, Inter } from "next/font/google";
import "./globals.css";

// الخط العربي
const ibmArabic = IBM_Plex_Sans_Arabic({
  variable: "--font-ar",
  subsets: ["arabic"],
  weight: ["300", "400", "500", "600", "700"],
});

// الخط اللاتيني (إذا تحتاج)
const interLatin = Inter({
  variable: "--font-lt",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar">
      <body
        className={`${ibmArabic.variable} ${interLatin.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
